pages:
  - source: 'terminals-shells-and-ssh/source.tsx'
    pathName: 'terminals-shells-and-ssh'
    pageTitle: 'Terminals, Shells, and SSH'
    namedIdentifier: 'terminals-shells-and-ssh'
  - source: 'basic-bash-commands/source.tsx'
    pathName: 'basic-bash-commands'
    pageTitle: 'Basic Bash Commands'
    namedIdentifier: 'basic-shell-commands'
  - source: 'vim/source.tsx'
    pathName: 'vim'
    pageTitle: 'Vim'
    namedIdentifier: 'terminal-based-text-editing'
  - source: 'python-hello-world/source.tsx'
    pathName: 'python-hello-world'
    pageTitle: 'Hello, World!'
    namedIdentifier: 'python-hello-world'
  - source: 'python-basics/source.tsx'
    pathName: 'python-basics'
    pageTitle: 'Python Basics'
    namedIdentifier: 'python-basics'
  - source: 'exceptions/source.tsx'
    pathName: 'exceptions'
    pageTitle: "Exceptions"
    namedIdentifier: 'exceptions'
  - source: 'file-io/source.tsx'
    pathName: 'file-io'
    pageTitle: "File I/O"
    namedIdentifier: 'file-io'
  - source: 'pod-types/source.tsx'
    pathName: 'pod-types'
    pageTitle: "POD Types"
    namedIdentifier: 'pod-types'
  - source: 'modules-and-packages/source.tsx'
    pathName: 'modules-and-packages'
    pageTitle: "Modules and Packages"
    namedIdentifier: 'modules-and-packages'
  - source: 'methods/source.tsx'
    pathName: 'methods'
    pageTitle: "Methods"
    namedIdentifier: 'methods'
  - source: 'encapsulation-and-information-hiding/source.tsx'
    pathName: 'encapsulation-and-information-hiding'
    pageTitle: "Encapsulation and Information Hiding"
    namedIdentifier: 'encapsulation-and-information-hiding'
  - source: 'pythons-basic-data-structures/source.tsx'
    pathName: 'pythons-basic-data-structures'
    pageTitle: "Python's Basic Data Structures"
    namedIdentifier: 'pythons-basic-data-structures'
