pages:
  - pathName: 'terminals-shells-and-ssh'
    pageTitle: 'Terminals, Shells, and SSH'
    namedIdentifier: 'terminals-shells-and-ssh'
  - pathName: 'basic-bash-commands'
    pageTitle: 'Basic Bash Commands'
    namedIdentifier: 'basic-shell-commands'
  - pathName: 'vim'
    pageTitle: 'Vim'
    namedIdentifier: 'terminal-based-text-editing'
  - pathName: 'python-hello-world'
    pageTitle: 'Hello, World!'
    namedIdentifier: 'python-hello-world'
  - pathName: 'python-basics'
    pageTitle: 'Python Basics'
    namedIdentifier: 'python-basics'
  - pathName: 'exceptions'
    pageTitle: 'Exceptions'
    namedIdentifier: 'exceptions'
  - pathName: 'file-io'
    pageTitle: 'File I/O'
    namedIdentifier: 'file-io'
  - pathName: 'pod-types'
    pageTitle: 'POD Types'
    namedIdentifier: 'pod-types'
  - pathName: 'modules-and-packages'
    pageTitle: 'Modules and Packages'
    namedIdentifier: 'modules-and-packages'
  - pathName: 'methods'
    pageTitle: 'Methods'
    namedIdentifier: 'methods'
  - pathName: 'encapsulation'
    pageTitle: 'Encapsulation'
    namedIdentifier: 'encapsulation'
  - pathName: 'none-and-optionals'
    pageTitle: 'None and Optionals'
    namedIdentifier: 'none-and-optionals'
  - pathName: 'references-and-copies'
    pageTitle: 'References and Copies'
    namedIdentifier: 'references-and-copies'
  - pathName: 'inheritance'
    pageTitle: 'Inheritance'
    namedIdentifier: 'inheritance'
  - pathName: 'polymorphism'
    pageTitle: 'Polymorphism'
    namedIdentifier: 'polymorphism'
  - pathName: 'generics'
    pageTitle: 'Generics'
    namedIdentifier: 'generics'
  - pathName: 'recursion'
    pageTitle: 'Recursion'
    namedIdentifier: 'recursion'
  - pathName: 'top-down-design'
    pageTitle: 'Top-down Design'
    namedIdentifier: 'top-down-design'
  - pathName: 'bottom-up-implementation-and-testing'
    pageTitle: 'Bottom-up Implementation and Testing'
    namedIdentifier: 'bottom-up-implementation-and-testing'
  - pathName: 'memory-models'
    pageTitle: 'Memory Models'
    namedIdentifier: 'memory-models'
  - pathName: 'pythons-basic-data-structures'
    pageTitle: "Python's Basic Data Structures"
    namedIdentifier: 'pythons-basic-data-structures'
