pages:
  - pathName: 'terminals-shells-and-ssh'
    pageTitle: 'Terminals, Shells, and SSH'
    namedIdentifier: 'terminals-shells-and-ssh'
  - pathName: 'basic-bash-commands'
    pageTitle: 'Basic Bash Commands'
    namedIdentifier: 'basic-shell-commands'
  - pathName: 'vim'
    pageTitle: 'Vim'
    namedIdentifier: 'terminal-based-text-editing'
  - pathName: 'c-in-context'
    pageTitle: 'C in Context'
    namedIdentifier: 'c-in-context'
  - pathName: 'hello-world'
    pageTitle: 'Hello, World!'
    namedIdentifier: 'hello-world'
  - pathName: 'c-basics'
    pageTitle: 'C Basics'
    namedIdentifier: 'c-basics'
  - pathName: 'pointers'
    pageTitle: 'Pointers'
    namedIdentifier: 'pointers'
  - pathName: 'strings'
    pageTitle: 'Strings'
    namedIdentifier: 'strings'
  - pathName: 'arrays'
    pageTitle: 'Arrays'
    namedIdentifier: 'arrays'
  - pathName: 'multidimensional-arrays'
    pageTitle: 'Multidimensional Arrays'
    namedIdentifier: 'multidimensional-arrays'
  - pathName: 'dynamic-memory'
    pageTitle: 'Dynamic Memory'
    namedIdentifier: 'dynamic-memory'
  - pathName: 'string-input-and-manipulation'
    pageTitle: 'String Input and Manipulation'
    namedIdentifier: 'string-input-and-manipulation'
  - pathName: 'dynamic-multidimensional-arrays'
    pageTitle: 'Dynamic Multidimensional Arrays'
    namedIdentifier: 'dynamic-multidimensional-arrays'
  - pathName: 'c-preprocessor'
    pageTitle: 'C Preprocessor'
    namedIdentifier: 'c-preprocessor'
  - pathName: 'file-separation'
    pageTitle: 'File Separation'
    namedIdentifier: 'file-separation'
  - pathName: 'structure-types'
    pageTitle: 'Structure Types'
    namedIdentifier: 'structure-types'
